### ISSUE TITLE
关于多栏滚动条的一点疑问

### ISSUE THREAD

**Issue by Mars687** [xclazy/2018IFE#1]
你好！自从star了你的这个项目，从你的代码中学到了很多。

最近在阅读https://github.com/xclazy/2018IFE/blob/master/basis/5/style.css 中的代码时有一点疑问，就是你在第6行重置了 html, body 的高度：
``` css 
/* reset */
html, body {
    height: 100%;
}
```
查了一些资料，如果 &lt;body&gt; 及其子元素的高度需要设置为窗口高度时，&lt;html&gt; 元素上也需要添加height: 100%;

对于这个小demo，如果不设定 html {height: 100%;}，会导致整个页面一起滚动（失去三栏分别滚动的效果）。

想请教你一下关于这里的理解，谢谢！
